### ISSUE TITLE
Android application crashes:  NimbusAdViewFragment.java - line 307

### ISSUE THREAD

**Issue by alien190** [freestarcapital/freestar_flutter_plugin#11]
freestar_flutter_plugin: ^1.0.3

Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1691)
       at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1731)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
       at androidx.fragment.app.DialogFragment.dismissInternal(DialogFragment.java:276)
       at androidx.fragment.app.DialogFragment.dismiss(DialogFragment.java:228)
       at com.adsbynimbus.ui.NimbusAdViewFragment.onAdEvent(NimbusAdViewFragment.java:307)
       at com.adsbynimbus.render.BaseAdController.dispatchAdEvent(BaseAdController.java:50)
       at com.adsbynimbus.render.ImaVideoAdController.onAdEvent(ImaVideoAdController.java:167)
       at com.google.ads.interactivemedia.v3.internal.dg.b(dg.java:10)
       at com.google.ads.interactivemedia.v3.internal.cv.b(cv.java:15)
       at com.google.ads.interactivemedia.v3.internal.ee.e(ee.java:44)
       at com.google.ads.interactivemedia.v3.internal.ek.d(ek.java:5)
       at com.google.ads.interactivemedia.v3.internal.eh.shouldOverrideUrlLoading(eh.java:2)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:73)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:14)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:325)
       at android.os.Looper.loop(Looper.java:142)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by alien190** [comment]
@kkawai Hello, thank you so much for fixing this issue. Today we published the new version of the app. I will observe crush reports next several days then update this conversation.
